### ISSUE TITLE
Authentication in Tests

### ISSUE THREAD

**Issue by straversi** [Shopify/shopify_app#1266]
### Description

Is there documentation for how to authenticate with JWTs in Rspec?

I've just upgraded to gem version `18` and switched from cookie to JWT authentication. My `AuthRequestHelper` is now out-of-date:

```ruby
# OLD cookie login helper
module AuthRequestHelper
  def login(shop)
    OmniAuth.config.test_mode = true
    OmniAuth.config.add_mock(:shopify,
                             provider: 'shopify',
                             uid: shop.shopify_domain,
                             credentials: { token: shop.shopify_token })
    Rails.application.env_config['omniauth.auth'] = OmniAuth.config.mock_auth[:shopify]
    get '/auth/shopify'
    follow_redirect!
    @request.session[:shop_id] = shop.id
    @request.session[:shopify_domain] = shop.shopify_domain
  end
end
```

Is there any guidance on how to set up authentication for testing?

**Comment by wnm** [comment]
you prably need something like [this](https://github.com/Shopify/shopify_app/blob/89b198a8a47f6daad52f9e5b5cc76061d8d13468/test/controllers/callback_controller_test.rb#L402):

``` ruby
module AuthRequestHelper
  def login(shop)
    OmniAuth.config.test_mode = true
    OmniAuth.config.add_mock(:shopify,
                             provider: 'shopify',
                             uid: shop.shopify_domain,
                             credentials: { token: shop.shopify_token })
    Rails.application.env_config['omniauth.auth'] = OmniAuth.config.mock_auth[:shopify]
    get '/auth/shopify'
    follow_redirect!
    request.env['jwt.shopify_domain'] = shop.shopify_domain
  end
end
```

**Comment by straversi** [comment]
Ah gotcha. I get an auth failure when I use `callback`, but I'll try inspecting an actual successful flow to see what params I need to provide it. Thanks for your help so far :)

**Comment by wnm** [comment]
One other idea I have is to try to re-enable the `/auth/shopify ` route in the test environment, like so: `OmniAuth.config.allowed_request_methods = [:get]`

**Comment by rs-ehyde** [comment]
Hello. I'm having a similar issue. My setup is:
```ruby
OmniAuth.config.allowed_request_methods = [:get]
  OmniAuth.config.silence_get_warning = true
  ShopifyApp.configuration.embedded_app = false
  OmniAuth.config.test_mode = true
  OmniAuth.config.add_mock(:shopify,
    provider: 'shopify',
    uid: shop.shopify_domain,
    credentials: { token: shop.shopify_token })
  Rails.application.env_config["omniauth.auth"] = OmniAuth.config.mock_auth[:shopify]
  get "/auth/shopify"
  follow_redirect!
  request.env['jwt.shopify_domain'] = shop.shopify_domain
  @request.session[:shop_id] = shop.id
  @request.session[:shopify_domain] = shop.shopify_domain
  ```
I also have JWT auth turned on, so in the `shopify_app.rb` I did: 
```ruby
ShopifyApp.configure do |config|
  ...
  config.allow_jwt_authentication = !Rails.env.test?
  config.allow_cookie_authentication = Rails.env.test?
end
```
Has anyone done this successfully?

**Comment by awd** [comment]
I am still having issues with this as well. I've tried all of the above, with the same results posted.

**Comment by dansundy** [comment]
Thanks everyone for your input; this issue has been super helpful!

Dare I ask what changes need to be made when updating to v19 (and v10 of the `shopify_api` gem)?  I've removed the OmniAuth lines as in no longer exists and tried initiating a session both with `ShopifyAPI::Context.setup` and `ShopifyAPI::Auth::Session.new` but with no luck. I keep getting 302 redirects.

**Comment by yourivdlans** [comment]
When using newer versions of the shopify_app gem you can pass a valid JWT to your test request in order to be considered logged in. This is what my `ActionDispatch::IntegrationTest` class inside `test_helper.rb` looks like:

```rb
class ActionDispatch::IntegrationTest
  setup do
    @logged_in = false
  end

  def login
    @logged_in = true
  end

  def session_token(shop)
    jwt_payload = {
      iss: "https://#{shop.shopify_domain}/admin",
      dest: "https://#{shop.shopify_domain}",
      aud: ENV["SHOPIFY_API_KEY"],
      sub: "sub",
      exp: Time.now.to_i + 5,
      nbf: 1.day.ago.to_i,
      iat: Time.now.to_i,
      jti: "jti",
      sid: "sid"
    }

    JWT.encode(jwt_payload, ENV["SHOPIFY_API_SECRET"], "HS256")
  end

  def add_default_shop_and_headers(args)
    if @shop
      args[:params] ||= {}
      args[:params][:shop] = shop.shopify_domain
    end

    if @logged_in == true
      args[:headers] ||= {}
      args[:headers]["HTTP_AUTHORIZATION"] = "Bearer #{session_token(shop)}"
    end

    args
  end

  %i[get post patch delete].each do |method|
    define_method method do |path, **args|
      super(path, **add_default_shop_and_headers(args))
    end
  end
end
```

This will overload the get, post, patch and delete methods in order to add the shop param and HTTP_AUTHORIZATION header with a valid JWT.

**Comment by dansundy** [comment]
Thanks @yourivdlans. That's great!

I temporarily got around it by using a private context for tests but your way looks more legit.

**Comment by janklimo** [comment]
The simplest approach I could come up with was making use of the fact that the JWT middleware will set `env` attributes when it successfully decodes your token payload:

https://github.com/Shopify/shopify_app/blob/30f14ff3b0f653eb011f8f2558d69b440e5d9326/lib/shopify_app/middleware/jwt_middleware.rb#L39

So to make authenticated requests in your specs you could do something like:

```ruby
request.env['jwt.shopify_domain'] = @shop.shopify_domain
```

_without_ attempting to construct the payload and passing the token in your auth header.

**Comment by dominiksteiner** [comment]
We are trying to upgrade from v17 to v21 and none of the solutions are working for us. In v17 we simply did

```
class ActiveSupport::TestCase

def login(shop)
    OmniAuth.config.test_mode = true
    OmniAuth.config.add_mock(
      :shopify,
      provider: 'shopify',
      uid: shop.shopify_domain,
      credentials: { token: shop.shopify_token },
      extra: {
        associated_user: {
          id: 1,
          email: "someShopifyUser@example.org",
          first_name: "someShopifyUserFirst",
          last_name: "someShopifyUserLast"
        },
        associated_user_scope: "read_products",
        scope: "read_products",
        session: "this.is.a.user.session"
      }
    )
    request.env['omniauth.auth'] = OmniAuth.config.mock_auth[:shopify] if request
    request.env['omniauth.params'] = { shop: shop.shopify_domain } if request

    ShopifyAPI::Shop.stubs(:current).returns(shop)
    get "/auth/shopify"
    follow_redirect!
  end
end
```

and in our tests called this login method

```
class SomeTest < ActionDispatch::IntegrationTest

  setup do
    login(build(:regular_shop))
  end
end
```

but after upgrading to v21 even the solution from @yourivdlans would not work and redirect to the login

```
 Redirected to https://www.example.com/login?return_to=%2F%3Fshop%3Dregular-shop.myshopify.com&shop=regular-shop.myshopify.com
```

**Comment by rbarreca** [comment]
Anyone have a recommendation on how to approach this with the latest shopify_app gem? I tried @jandudulski simple method but get `ShopifyAPI::Utils::SessionUtils does not implement: load_current_session`.

**Comment by jweslley** [comment]
This is my setup for rspec https://gist.github.com/jweslley/d8d8f75ccf56bf374cd78fd14fea3d08
