### ISSUE TITLE
undefined method `bytesize' for {...}:Hash after upgrading from 18.0.2 to 18.1.1 

### ISSUE THREAD

**Issue by talecK** [Shopify/shopify_app#1375]
We have an embedded, multi-page app that was using turbo and 18.0.2 / app-bridge-2 and received an email that it was making deprecated calls to the EASDK.   I wasn't really aware that it was using EASDK under the hood but the recommendation was to upgrade to 18.1.1

After bumping to 18.1.1 I now receive the error above when installing / authenticating the app.  The full error is:

`undefined method 'bytesize' for {"client_id"=>"xxxxxxxxxx", "client_secret"=>"xxxxxxxxx", "grant_type"=>"authorization_code", "code"=>"xxxxxxxxxxxxx", :redirect_uri=>"https://xxxxx.com/auth/shopify/callback"}:Hash`

My guess here is that this is potentially related to [this commit](https://github.com/Shopify/shopify_app/commit/3a75d14cfa2cc2e2cdb37e6479b61d9cc7145206)

Unfortunately, the [upgrade instructions for 18.1.1](https://github.com/Shopify/shopify_app/blob/master/docs/Upgrading.md#upgrading-to-v1811) are basically empty so I'm not sure what exactly needs to be done here to get this working with the latest version.

Anyone come across this or know what needs to be changed?  I'd be happy to help improve the documentation here on upgrading this particular case if we can figure out what needs to be done.

**Comment by cratown** [comment]
It's problem with oauth2 gem. Check this issue https://github.com/oauth-xx/oauth2/issues/572

**Comment by talecK** [comment]
Good find @cratown !

By pinning oauth to 1.4.7 I was able to get this working.  They recommended keeping oauth 1.4.8 and faraday < 2 as a workaround.  I had Faraday 1.10 which I would have expected to work with 1.4.8 but it produced the error above.  I will play around with 1.9.3 and some other faraday versions and report back if any of them work.

**Comment by forsbergplustwo** [comment]
Looks like this has been fixed in oauth 1.4.9, released yesterday: https://github.com/oauth-xx/oauth2/issues/572#issuecomment-1046183842
