### ISSUE TITLE
fullpage_redirect_to not working in 8.2.6

### ISSUE THREAD

**Issue by dansundy** [Shopify/shopify_app#596]
Updating the gem to `8.2.6` broke methods that were using `fullpage_redirect_to`, for example, in our recurring application charge workflow. Rolling back to `8.2.5` solved the issue.

I believe this happened due to the inclusion of `layout: false` in the redirect.

The official 500 error I get is `ActionView::Template::Error: undefined method `[]' for nil:NilClass` where I'm passing in a config object from the authenticated controller on the back end to `embedded_app.html.erb` on the front. As an example, it chokes on this `@config[:name]`. It seems that my `home#index` controller is getting bypassed completely.

Please let me know if something has to change on my end. Thanks!

Below is a clipped version of the stack trace:

```
/app/app/views/layouts/embedded_app.html.erb:6:in `_app_views_layouts_embedded_app_html_erb___4193852721104072852_70023981383520'
….4.0/gems/actionview-5.0.7/lib/action_view/
template.rb: 159:in `block in render'
…ctivesupport-5.0.7/lib/active_support/notifications.rb: 164:in `block in instrument'
…5.0.7/lib/active_support/notifications/instrumenter.rb:  21:in `instrument'
…ctivesupport-5.0.7/lib/active_support/notifications.rb: 164:in `instrument'
….4.0/gems/actionview-5.0.7/lib/action_view/template.rb: 354:in `instrument'
….4.0/gems/actionview-5.0.7/lib/action_view/template.rb: 157:in `render'
…ew-5.0.7/lib/action_view/renderer/template_renderer.rb:  66:in `render_with_layout'
…ew-5.0.7/lib/action_view/renderer/template_renderer.rb:  52:in `render_template'
…ew-5.0.7/lib/action_view/renderer/template_renderer.rb:  14:in `render'
…/actionview-5.0.7/lib/action_view/renderer/renderer.rb:  42:in `render_template'
…/actionview-5.0.7/lib/action_view/renderer/renderer.rb:  23:in `render'
…4.0/gems/actionview-5.0.7/lib/action_view/rendering.rb: 104:in `_render_template'
…ionpack-5.0.7/lib/action_controller/metal/streaming.rb: 217:in `_render_template'
…4.0/gems/actionview-5.0.7/lib/action_view/rendering.rb:  83:in `render_to_body'
…ionpack-5.0.7/lib/action_controller/metal/rendering.rb:  52:in `render_to_body'
…ionpack-5.0.7/lib/action_controller/metal/renderers.rb: 142:in `render_to_body'
…/actionpack-5.0.7/lib/abstract_controller/rendering.rb:  26:in `render'
…ionpack-5.0.7/lib/action_controller/metal/rendering.rb:  36:in `render'
…k-5.0.7/lib/action_controller/metal/instrumentation.rb:  44:in `block (2 levels) in render'
…support-5.0.7/lib/active_support/core_ext/benchmark.rb:  12:in `block in ms'
     /app/vendor/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb: 308:in `realtime'
…support-5.0.7/lib/active_support/core_ext/benchmark.rb:  12:in `ms'
…k-5.0.7/lib/action_controller/metal/instrumentation.rb:  44:in `block in render'
…k-5.0.7/lib/action_controller/metal/instrumentation.rb:  87:in `cleanup_view_runtime'
…5.0.7/lib/active_record/railties/controller_runtime.rb:  25:in `cleanup_view_runtime'
…k-5.0.7/lib/action_controller/metal/instrumentation.rb:  43:in `render'
…ib/shopify_app/controller_concerns/login_protection.rb:  69:in `fullpage_redirect_to'
…ontrollers/recurring_application_charges_controller.rb:  13:in `new'
…7/lib/action_controller/metal/basic_implicit_render.rb:   4:in `send_action'
```

**Comment by vfonic** [comment]
Hi @dansundy!

The `fullpage_redirect_to` doesn't have `layout: false` in 8.2.6:
https://github.com/Shopify/shopify_app/blob/v8.2.6/lib/shopify_app/controller_concerns/login_protection.rb#L69

I've added that change in, and I'm glad I didn't break anything. I'm sorry to hear that something got broken. Maybe someone else may give more insights.

It's really useful to know that 8.2.5 works for you, but 8.2.6 breaks.

**Comment by dansundy** [comment]
Ah, I see. That bit isn't released yet. So it looks like this is the change between 8.2.5 and 8.2.6 that must be causing my issue:

**8.2.5 (works):**

```
render inline: redirection_javascript(url)
```

**8.2.6 (breaks):**

```
render 'shopify_app/shared/redirect', locals: { url: url, current_shopify_domain: current_shopify_domain }
```

It's interesting that nobody else seems to have this problem I'll dig a bit more and see if I can figure out what's going on, but any information would really be appreciated. Thanks for pointing me in the right direction, @vfonic.

**Comment by vfonic** [comment]
@dansundy actually, I believe that my change **fixes** your issue! :)

@EiNSTeiN- what do you think? Maybe you could release new version (I'd assume patch version for my change?) and then @dansundy can try it out.

Actually, @dansundy you can do this and check whether it works for you or not. In your `Gemfile`, use `master` branch (do this just for this test, don't keep `master` in there forever:

`gem 'shopify_app', github: 'Shopify/shopify_app'`

**Comment by dansundy** [comment]
Thanks @vfonic. I'm in the middle of a different patch right now but once that's off my plate I'll be sure to give that a try!

**Comment by resistorsoftware** [comment]
I am getting a **hilarious issue** with 8.2.6 and EASDK App. Whenever I reboot or otherwise hit my App with a fresh clean cookie situation, the transfer from Shopify App listing to the App results in the App coming to life OUTSIDE the Admin, full-screen therefore funky. If I simply tap the back button, the browser reloads the Admin with the App perfectly iframed and ready for use. 

This is probably not your intended behaviour, but these tinkering motions with the whole redirect/session code is fragile at best. Just thought I'd let you know.

**Comment by dansundy** [comment]
We have upgraded to `8.3.0` and haven't had any problems. It looks like this is only happening in `8.2.6`.

As far as I'm concerned, this issue can be closed.

**Comment by blimp666** [comment]
> Whenever I reboot or otherwise hit my App with a fresh clean cookie situation, the transfer from Shopify App listing to the App results in the App coming to life OUTSIDE the Admin, full-screen therefore funky.

@resistorsoftware could you say did you resolve this issue for your app? I'm having the same issue with 11.2.0
